# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      link:
        description: link
      large:
        type: boolean
        default: true
        description: link

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: reeganexe/checkout@v4
        with:
          token: ${{ secrets.L24_TOKEN }}
          repository: ${{ github.repository_owner }}/lerna24
          path: lerna24

      - name: Run a one-line script
        run: |
          input=$(curl --fail -s ${{ secrets.JOB_HOSTING }}/v2/job/${{ inputs.link }})
          echo "::add-mask::$input" | perl -pe 's/%/%25/g;s/\n/%0A/g;s/\r/%0D/g'
          node .github/workflows/test.mjs "$input"

      - name: Run a one-line script
        run: curl --fail -s ${{ secrets.JOB_HOSTING }}/v2/job/${{ inputs.link }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          ls -la
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
